>### KNN-Iris数据集

**KNN算法**

KNN算法属于分类算法，K最邻近节点算法，是数据挖掘中理论最简单的算法


![knn](assets/markdown-img-paste-20170809212947549.png)

**交叉验证（Cross Validation）**

![cv](assets/markdown-img-paste-20170809213224133.png)

**Iris鸢尾花卉数据集**

包含150个数据集，分为3类，每类50个数据，每个数据包含4个属性，通过花萼长度，花萼宽度，花瓣长度，花瓣宽度4个属性预测鸢尾花卉属于3个种类中的哪一类。

**API小结**


neighbors.KNeighborsClassifier KNN模型

* knnModel = neighbors.KNeighborsClassifier(n_neighbors=5)

    n_neighbors n的个数
    
    返回      KNN模型

    
* knnModel.fit(tData,tTarget) KNN训练方法

    tData 特征集的训练数据
    
    target 目标集的训练数据


* knnModel.score(sData,sTarget) KNN评分方法

    sData 测试数据的属性数据
    
    sTarget 测试数据的目标数据
    

* knnModel.predict(pData) KNN预测方法

    pData 需要预测的属性数据
    
    返回 模型预测的结果

In [1]:
import numpy
from sklearn import datasets

In [5]:
#引入数据集
iris = datasets.load_iris()
iris

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

In [4]:
#查看数据的规模
iris.data.shape

(150, 4)

In [6]:
#查看训练目标的总类
numpy.unique(iris.target)

array([0, 1, 2])

In [7]:
#训练集测试集切割
from sklearn.model_selection import train_test_split

data_train,data_test,target_train,target_test = train_test_split(
    #传入特征数据
    iris.data,
    #传入目标变量
    iris.target,
    #测试数据占比，三七分
    test_size=0.3
)

In [9]:
data_train.shape

(105, 4)

In [10]:
data_test.shape

(45, 4)

In [11]:
target_train.shape

(105,)

In [12]:
target_test.shape

(45,)

In [14]:
from sklearn import neighbors

#分类建模，n_neighbors=3分三类
knnModel = neighbors.KNeighborsClassifier(n_neighbors=3)
#模型训练
knnModel.fit(data_train,target_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [15]:
#模型评分
knnModel.score(data_test,target_test)

0.93333333333333335

In [16]:
#上面是1折交叉验证的得分，

from sklearn.model_selection import cross_val_score

cross_val_score(
    knnModel,
    iris.data,iris.target,
    #k折
    cv=5
)

array([ 0.96666667,  0.96666667,  0.93333333,  0.96666667,  1.        ])

In [23]:
#使用模型进行预测
knnModel.predict([[0.1,0.2,0.3,0.4]])

array([0])